# This is a basic workflow to help you get started with Actions

name: ppc64le runner ci

env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}
  IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
  ARCH: ${{ secrets.ARCH }}
  PYXIS_API_TOKEN: ${{ secrets.PYXIS_API_TOKEN }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build
  ppc64le:
      runs-on: ppc64le
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install preflight 
        run: |
          wget https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/download/1.2.0/preflight-linux-"$ARCH"
          chmod u+x preflight-linux-"$ARCH"
          sudo mv preflight-linux-"$ARCH" /usr/local/bin/preflight
          preflight --version
 
      - name: Check container-image
        run: |
          preflight check container "$IMAGE_REGISTRY"/"$IMAGE_NAMESPACE"/"$IMAGE_NAME":"$IMAGE_TAG"
